### ISSUE TITLE
Amazon messages hidden in text

### ISSUE THREAD

**Issue by Krynh** [sgprinc/RoyalRoadScraper#1]
Appreciate wanting to keep stolen works off Amazon, but do you need to keep filling the scraped chapters with a message that the chapters should be reported? It's a pain to remove

**Comment by roverton** [comment]
This is detected and done by royal road. They've started using what looks like an LLM to generate increasingly complex insert messages. It's because the site detects that the scraper is not a real web browser with a human reading.

Not really a fault of this program and trying to mitigate it would just start an unnecessary arms race.

I just write a simple grep/sed script to remove those messages on my own. It's fairly trivial if occasionally a bit time consuming when royal road changes up the message injection formatting.
